name: Python-package

on:
  push:
    branches:
    - test-install

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  SKBUILD_STRICT_CONFIG: true

jobs:
  test:
    name: ${{ matrix.task }} ${{ matrix.method }} (${{ matrix.os }}, Python ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
    steps:
      - name: Setup
        shell: bash
        run: |
          bash <(curl -s https://raw.githubusercontent.com/microsoft/LightGBM/refs/heads/test-install/.ci/setup.sh) || exit 1
